[package]
name = "veryl-discovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow      = "1.0"
clap        = {version = "4.5.7", features = ["derive"]}
chrono      = {version = "0.4.38", features = ["serde"]}
http        = "1.1"
octocrab    = "0.38.0"
plotters    = "0.3.6"
reqwest     = "0.12.4"
secrecy     = "0.8.0"
semver      = "1.0"
serde       = {version = "1.0", features = ["derive"]}
serde_json  = "1.0"
tokio       = {version = "1.38.0", features = ["full"]}
url         = "2.5"
walkdir     = "2.5"
which       = "6.0"
zip-extract = "0.1.3"
