name: Periodic

on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * SUN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
    - uses: Swatinem/rust-cache@v2
    - name: Run
      run: cargo run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Update db"
        add: "./db/*"
        fetch: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
